# Generated by Django 6.0 on 2025-12-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locataire",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="locataire",
            name="prenom",
        ),
        migrations.RemoveField(
            model_name="proprietaire",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="proprietaire",
            name="prenom",
        ),
    ]
