# Generated by Django 6.0 on 2025-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0002_remove_locataire_nom_remove_locataire_prenom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locataire",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="proprietaire",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
