# Generated by Django 6.0 on 2025-12-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0003_remove_locataire_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
