# Generated by Django 6.0 on 2025-12-27 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0006_remove_user_token_created_at_user_token_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 23, 31, 8, 367295, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
