# Generated by Django 6.0 on 2025-12-28 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0008_alter_user_token_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 29, 0, 25, 1, 828169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
