# Generated by Django 6.0 on 2026-01-10 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0009_alter_user_token_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("proprietaire", "Proprietaire"), ("locataire", "Locataire")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 11, 19, 1, 54, 978488, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
