# Generated by Django 6.0 on 2026-01-11 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0010_alter_user_role_alter_user_token_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="moyen_connexion",
            field=models.CharField(default="standard", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 12, 17, 55, 11, 129057, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
